---
- hosts: centos
  tasks:
    - name : copy file to server
      copy: src=test.sh dest=/home/centos/test.sh mode=0755
    - name: Run the script
      command: /home/centos/test.sh
      register:  comm_out
      ignore_errors: yes
    - debug: msg= "STDOUT - {{ comm_out.stdout }} desu"
    - debug: msg="STDERR - {{ comm_out.stderr }} desu"